-- ==============================================================
-- DOMRS Database Schema (Supabase)
-- Run this in the Supabase SQL Editor to create the necessary tables
-- Three roles: eoc, institution, civilian  (PHO absorbed into EOC)
-- ==============================================================

-- 1. Enums
CREATE TYPE user_role        AS ENUM ('eoc', 'institution', 'civilian');
CREATE TYPE facility_status  AS ENUM ('pending', 'approved', 'rejected', 'blacklisted');
CREATE TYPE alert_status     AS ENUM ('pending_investigation', 'investigating', 'probable', 'confirmed', 'invalidated');
CREATE TYPE report_status    AS ENUM ('Pending AI', 'AI Scored', 'Under EOC Review', 'Validated', 'Dismissed');
CREATE TYPE advisory_severity AS ENUM ('ADVISORY', 'WARNING', 'CRITICAL');

-- 2. Profiles (extends auth.users)
CREATE TABLE public.profiles (
    id           UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email        TEXT NOT NULL,
    role         user_role DEFAULT 'civilian'::user_role NOT NULL,
    first_name   TEXT,
    last_name    TEXT,
    organization_id TEXT,   -- UUID string of the linked facility (institution users only)
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Facilities
CREATE TABLE public.facilities (
    id               UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name             TEXT NOT NULL,
    status           facility_status DEFAULT 'pending'::facility_status NOT NULL,
    verified_at      TIMESTAMP WITH TIME ZONE,
    blacklist_reason TEXT,
    last_report_at   TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. AI Alerts (generated by CBS scoring engine after each report)
CREATE TABLE public.ai_alerts (
    id               UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    report_id        UUID,                              -- source sentinel report (informational)
    facility_id      TEXT,                              -- mirrors organization_id (TEXT, no FK, flexible)
    zone_id          TEXT NOT NULL,
    cbs_score        FLOAT NOT NULL,                   -- Confidence-Based Score 0.00–1.00
    severity_index   INTEGER,                          -- ceil(CBS × 10), 1–10
    status           alert_status DEFAULT 'pending_investigation'::alert_status,
    symptom_weight   FLOAT,
    bypass_reason    TEXT,                             -- set on CRITICAL_BYPASS_HEMORRHAGIC
    investigated_by  UUID REFERENCES public.profiles(id),
    investigated_at  TIMESTAMP WITH TIME ZONE,
    overridden_by    UUID REFERENCES public.profiles(id),
    override_reason  TEXT,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Sentinel Reports
CREATE TABLE public.sentinel_reports (
    id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    submitted_by    UUID REFERENCES public.profiles(id),   -- NULL allowed for community/anonymous
    organization_id TEXT,                                   -- facility UUID string; NULL for community reports
    source          TEXT DEFAULT 'institution' CHECK (source IN ('institution', 'community')),
    alert_id        UUID REFERENCES public.ai_alerts(id),  -- populated after CBS scoring
    patient_count   INTEGER NOT NULL,
    origin_lat      FLOAT NOT NULL,
    origin_lng      FLOAT NOT NULL,
    origin_address  TEXT,
    symptom_matrix  JSONB NOT NULL,
    severity        INTEGER NOT NULL CHECK (severity >= 1 AND severity <= 10),
    notes           TEXT,
    status          report_status DEFAULT 'Pending AI'::report_status NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Advisories (issued by EOC, visible to all institutions)
CREATE TABLE public.advisories (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    facility_id UUID REFERENCES public.facilities(id),
    zone_id     TEXT NOT NULL,
    message     TEXT NOT NULL,
    severity    advisory_severity NOT NULL,
    issued_by   UUID REFERENCES public.profiles(id),
    dismissed   BOOLEAN DEFAULT false,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Response Protocols (reference library, EOC-managed)
CREATE TABLE public.response_protocols (
    id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    disease_id TEXT NOT NULL,
    title      TEXT NOT NULL,
    content    TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================
-- Trigger: auto-create profile row on new auth user signup
-- ==============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, first_name, last_name, role, organization_id)
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'firstName',
    new.raw_user_meta_data->>'lastName',
    COALESCE((new.raw_user_meta_data->>'role')::user_role, 'civilian'::user_role),
    new.raw_user_meta_data->>'organizationId'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==============================================================
-- Live DB migration (run these on an existing deployment)
-- ==============================================================
-- ALTER TABLE public.profiles         DROP COLUMN IF EXISTS can_broadcast;
-- ALTER TABLE public.facilities       DROP COLUMN IF EXISTS data_quality_score;
-- ALTER TABLE public.sentinel_reports DROP COLUMN IF EXISTS professional_id_hash;
-- ALTER TABLE public.sentinel_reports ADD COLUMN IF NOT EXISTS
--     source TEXT DEFAULT 'institution' CHECK (source IN ('institution', 'community'));
-- ALTER TABLE public.sentinel_reports ALTER COLUMN submitted_by DROP NOT NULL;
-- ALTER TABLE public.sentinel_reports ALTER COLUMN organization_id DROP NOT NULL;
-- ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'civilian';  -- no-op if exists
-- (To remove 'pho' from the enum requires recreating it — only needed on a fresh DB)
